name: build-time-project


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted
  
    steps:
      - uses: AutoModality/action-clean@v1   
      - uses: actions/checkout@v2
      

