name: build-time-project


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted
  
    steps:
    
      - uses: AutoModality/action-clean@v1   
      
      - uses: actions/checkout@v2
      
      - name: Stop container
        run:  |
          docker container stop our-website_nginx_1
          
      - name: Remove container
        run:  |
          docker container stop our-website_nginx_1
          
      - name: Run the container
        run: |     
          git update-index --chmod=+x /home/ubuntu/front/actions-runner/_work/our-website/our-website/init-letsencrypt.sh  
          
      - name: Run the container
        run: |
          ./init-letsencrypt.sh  
          
      
      - name: Run the container
        run: |
          docker-compose up -d
