name: build-time-project


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted
  
    steps:
      - name: delete content
        run: |
          sudo mv ./*  /var/www/itunique_net/html
